In [1]:
import gwaslab as gl 
import genal
from config import *
import pandas as pd

/home/xutingfeng/miniforge3/envs/postGWAS/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html


## Load Data

1. The `gl.Sumstats` module supports loading data from various sources such as directories, Pandas DataFrames, and more.
2. You can build a pipeline to convert and save raw summary statistics into supported formats. Several commonly used formats are already supported — see the [formats directory](https://github.com/Cloufield/formatbook/tree/main/formats) for details (e.g., GWAS Catalog format).

> **Note:** When working with large datasets, using CSV or gzip-compressed files can be time-consuming. It is highly recommended to preprocess your data and save it in the `feather` format for significantly faster loading and downstream analysis.

In [ ]:
%%time
filename = "GCST90449056.tsv.gz"
data = pd.read_csv(data_dir / filename, sep = r"\s+", compression="gzip")
data

,chromosome,base_pair_location,effect_allele,other_allele,beta,standard_error,effect_allele_frequency,p_value,rs_id,n
0,1,752566,G,A,-0.003855,0.002427,0.1637,0.112194,rs3094315,663139
1,1,885689,G,A,-0.012647,0.004002,0.0537,0.001575,rs4970452,656956
2,1,885699,A,G,-0.012867,0.003977,0.0544,0.001216,rs4970376,656954
3,1,886006,T,C,-0.012928,0.003981,0.0543,0.001164,rs4970375,656955
4,1,887801,A,G,-0.012811,0.003977,0.0544,0.001278,rs3828047,656954
...,...,...,...,...,...,...,...,...,...,...
5753790,22,51172460,C,T,-0.004041,0.005831,0.0225,0.488332,rs5770824,715356
5753791,22,51175626,G,A,0.001762,0.003547,0.0613,0.619277,rs3810648,739079
5753792,22,51177257,T,C,-0.000743,0.004725,0.0348,0.875139,rs73174437,713374
5753793,22,51178090,A,G,0.001494,0.003735,0.0549,0.689183,rs2285395,739077
5753794,22,51182399,G,A,0.000592,0.003232,0.0770,0.854675,rs56238942,720624

This summary statistics file was downloaded directly from the GWAS Catalog, it's already in a supported format. That means you can load it without needing additional conversion:

>Note: This file was downloaded from the GWAS Catalog, so we can load it directly using `gl.Sumstats()`.

As rsid may not always be present in the summary statistics, so we can check or

In [ ]:
# define fmt_dict to map columns
fmt_dict = dict(
    fmt = "gwascatalog",
    build = "38"  # check genome build or versionConvert in the beginning
)
if "rs_id" in data.columns:
    fmt_dict["rsid"] = "rs_id"
if "n" in data.columns:
    fmt_dict["n"] = "n"

if "snpid" in data.columns:
    fmt_dict["snpid"] = "variant_id"

sumstats = gl.Sumstats(
    sumstats=data,
    **fmt_dict
)
sumstats.data

2025/06/10 01:27:22 GWASLab v3.6.3 https://cloufield.github.io/gwaslab/
2025/06/10 01:27:22 (C) 2022-2025, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2025/06/10 01:27:22 Python version: 3.9.23 | packaged by conda-forge | (main, Jun  4 2025, 17:57:12)
[GCC 13.3.0]
2025/06/10 01:27:22 Start to load format from formatbook....
2025/06/10 01:27:22  -gwascatalog format meta info:
2025/06/10 01:27:22   - format_name  : gwascatalog
2025/06/10 01:27:22   - format_source  : https://www.ebi.ac.uk/gwas/docs/methods/summary-statistics
2025/06/10 01:27:22   - format_version  : 20220726
2025/06/10 01:27:22  -gwascatalog to gwaslab format dictionary:
2025/06/10 01:27:22   - gwascatalog keys: variant_id,chromosome,base_pair_location,other_allele,effect_allele,beta,effect_allele_frequency,standard_error,p-value,odds_ratio,ci_lower,ci_upper
2025/06/10 01:27:22   - gwaslab values: SNPID,CHR,POS,NEA,EA,BETA,EAF,SE,P,OR,OR_95L,OR_95U
2025/06/10 01:27:22 Start to initialize gl.Sumstats from pandas DataFrame ...
2025/06/10 01:27:24  -Reading columns          : other_allele,beta,chromosome,rs_id,effect_allele_frequency,standard_error,base_pair_location,n,effect_allele
2025/06/10 01:27:24  -Renaming columns to      : NEA,BETA,CHR,rsID,EAF,SE,POS,N,EA
2025/06/10 01:27:24  -Current Dataframe shape : 5753795  x  9
2025/06/10 01:27:24  -Initiating a status column: STATUS ...
2025/06/10 01:27:24  -Genomic coordinates are based on GRCh38/hg38...
2025/06/10 01:27:25 Start to reorder the columns...v3.6.3
2025/06/10 01:27:25  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 367.16 MB
2025/06/10 01:27:25  -Reordering columns to    : rsID,CHR,POS,EA,NEA,EAF,BETA,SE,N,STATUS
2025/06/10 01:27:25 Finished reordering the columns.
2025/06/10 01:27:25  -Column  : rsID   CHR   POS   EA       NEA      EAF     BETA    SE      N     STATUS
2025/06/10 01:27:25  -DType   : object Int64 int64 category category float64 float64 float64 int64 category
2025/06/10 01:27:25  -Verified: T      T     T     T        T        T       T       T       T     T
2025/06/10 01:27:25  -Current Dataframe memory usage: 367.16 MB
2025/06/10 01:27:25 Finished loading data successfully!

,rsID,CHR,POS,EA,NEA,EAF,BETA,SE,N,STATUS
0,rs3094315,1,752566,G,A,0.1637,-0.003855,0.002427,663139,3899999
1,rs4970452,1,885689,G,A,0.0537,-0.012647,0.004002,656956,3899999
2,rs4970376,1,885699,A,G,0.0544,-0.012867,0.003977,656954,3899999
3,rs4970375,1,886006,T,C,0.0543,-0.012928,0.003981,656955,3899999
4,rs3828047,1,887801,A,G,0.0544,-0.012811,0.003977,656954,3899999
...,...,...,...,...,...,...,...,...,...,...
5753790,rs5770824,22,51172460,C,T,0.0225,-0.004041,0.005831,715356,3899999
5753791,rs3810648,22,51175626,G,A,0.0613,0.001762,0.003547,739079,3899999
5753792,rs73174437,22,51177257,T,C,0.0348,-0.000743,0.004725,713374,3899999
5753793,rs2285395,22,51178090,A,G,0.0549,0.001494,0.003735,739077,3899999
5753794,rs56238942,22,51182399,G,A,0.0770,0.000592,0.003232,720624,3899999

standarization of data to remove dup and fix some errors, so the data can be suitable for further analysis

In [17]:
n_cores = 6 # or by number of cores
sumstats.basic_check(remove=True,remove_dup=True, n_cores=n_cores)

2025/06/10 01:28:44 Start to check SNPID/rsID...v3.6.3
2025/06/10 01:28:44  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 356.19 MB
2025/06/10 01:28:44  -Checking rsID data type...
2025/06/10 01:28:44  -Checking if rsID is rsxxxxxx...
2025/06/10 01:28:51  -Checking if CHR:POS:NEA:EA is mixed in rsID column ...
2025/06/10 01:28:53  -Number of CHR:POS:NEA:EA mixed in rsID column : 0
2025/06/10 01:28:54  -Number of Unrecognized rsID : 0
2025/06/10 01:28:54  -A look at the unrecognized rsID : set() ...
2025/06/10 01:28:54 Finished checking SNPID/rsID.
2025/06/10 01:28:54 Start to fix chromosome notation (CHR)...v3.6.3
2025/06/10 01:28:54  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 356.19 MB
2025/06/10 01:28:54  -Checking CHR data type...
2025/06/10 01:28:55  -Variants with standardized chromosome notation: 5753795
2025/06/10 01:28:56  -All CHR are already fixed...
2025/06/10 01:29:01 Finished fixing chromosome notation (CHR).
2025/06/10 01:29:01 Start to fix basepair positions (POS)...v3.6.3
2025/06/10 01:29:01  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 356.19 MB
2025/06/10 01:29:01  -Converting to Int64 data type ...
2025/06/10 01:29:07  -Position bound:(0 , 250,000,000)
2025/06/10 01:29:07  -Removed outliers: 0
2025/06/10 01:29:08  -Removed 0 variants with bad positions.
2025/06/10 01:29:08 Finished fixing basepair positions (POS).
2025/06/10 01:29:08 Start to fix alleles (EA and NEA)...v3.6.3
2025/06/10 01:29:08  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 400.09 MB
2025/06/10 01:29:08  -Converted all bases to string datatype and UPPERCASE.
2025/06/10 01:29:09  -Variants with bad EA  : 0
2025/06/10 01:29:10  -Variants with bad NEA : 0
2025/06/10 01:29:10  -Variants with NA for EA or NEA: 0
2025/06/10 01:29:10  -Variants with same EA and NEA: 0
2025/06/10 01:29:11  -Removed 0 variants with NA alleles or alleles that contain bases other than A/C/T/G.
2025/06/10 01:29:12  -Removed 0 variants with same allele for EA and NEA.
2025/06/10 01:29:17 Finished fixing alleles (EA and NEA).
2025/06/10 01:29:18 Start to perform sanity check for statistics...v3.6.3
2025/06/10 01:29:18  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 400.09 MB
2025/06/10 01:29:18  -Comparison tolerance for floats: 1e-07
2025/06/10 01:29:18  -Checking if 0 <= N <= 2147483647 ...
2025/06/10 01:29:19  -Removed 0 variants with bad/na N.
2025/06/10 01:29:19  -Checking if -1e-07 < EAF < 1.0000001 ...
2025/06/10 01:29:19  -Removed 0 variants with bad/na EAF.
2025/06/10 01:29:19  -Checking if -100.0000001 < BETA < 100.0000001 ...
2025/06/10 01:29:20  -Removed 0 variants with bad/na BETA.
2025/06/10 01:29:20  -Checking if -1e-07 < SE < inf ...
2025/06/10 01:29:21  -Removed 0 variants with bad/na SE.
2025/06/10 01:29:21  -Checking STATUS and converting STATUS to categories....
2025/06/10 01:29:22  -Removed 0 variants with bad statistics in total.
2025/06/10 01:29:22  -Data types for each column:
2025/06/10 01:29:22  -Column  : rsID   CHR   POS   EA       NEA      EAF     BETA    SE      N     STATUS
2025/06/10 01:29:22  -DType   : string Int64 Int64 category category float32 float64 float64 Int64 category
2025/06/10 01:29:22  -Verified: T      T     T     T        T        T       T       T       T     T
2025/06/10 01:29:22 Finished sanity check for statistics.
2025/06/10 01:29:22 Start to check data consistency across columns...v3.6.3
2025/06/10 01:29:22  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 400.09 MB
2025/06/10 01:29:22  -Tolerance: 0.001 (Relative) and 0.001 (Absolute)
2025/06/10 01:29:22  -No availalbe columns for data consistency checking...Skipping...
2025/06/10 01:29:22 Finished checking data consistency across columns.
2025/06/10 01:29:22 Start to normalize indels...v3.6.3
2025/06/10 01:29:22  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 400.09 MB
2025/06/10 01:29:24  -No available variants to normalize..
2025/06/10 01:29:24 Finished normalizing variants successfully!
2025/06/10 01:29:24 Start to remove duplicated/multiallelic variants...v3.6.3
2025/06/10 01:29:24  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 400.09 MB
2025/06/10 01:29:24  -Removing mode:dm
2025/06/10 01:29:24 ColumnP was not detected... skipping...
2025/06/10 01:29:24 Start to remove duplicated variants based on rsID...
2025/06/10 01:29:24  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 400.09 MB
2025/06/10 01:29:28  -Removed  0  based on rsID...
2025/06/10 01:29:28 Start to remove duplicated variants based on CHR,POS,EA and NEA...
2025/06/10 01:29:28  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 400.09 MB
2025/06/10 01:29:28  -Which variant to keep:  first
2025/06/10 01:29:28 Start to remove multiallelic variants based on chr:pos...
2025/06/10 01:29:28  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 400.09 MB
2025/06/10 01:29:28  -Which variant to keep:  first
2025/06/10 01:29:31  -Removed  0  multiallelic variants...
2025/06/10 01:29:31  -Removed  0  variants in total.
2025/06/10 01:29:31  -Sort the coordinates based on CHR and POS...
2025/06/10 01:29:35 Finished removing duplicated/multiallelic variants.
2025/06/10 01:29:35 Start to sort the genome coordinates...v3.6.3
2025/06/10 01:29:35  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 356.19 MB
2025/06/10 01:29:38 Finished sorting coordinates.
2025/06/10 01:29:38 Start to reorder the columns...v3.6.3
2025/06/10 01:29:38  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 356.19 MB
2025/06/10 01:29:38  -Reordering columns to    : rsID,CHR,POS,EA,NEA,EAF,BETA,SE,N,STATUS
2025/06/10 01:29:38 Finished reordering the columns.

In [18]:
sumstats.data

,rsID,CHR,POS,EA,NEA,EAF,BETA,SE,N,STATUS
0,rs3094315,1,752566,G,A,0.1637,-0.003855,0.002427,663139,3850099
1,rs4970452,1,885689,G,A,0.0537,-0.012647,0.004002,656956,3850099
2,rs4970376,1,885699,A,G,0.0544,-0.012867,0.003977,656954,3850099
3,rs4970375,1,886006,T,C,0.0543,-0.012928,0.003981,656955,3850099
4,rs3828047,1,887801,A,G,0.0544,-0.012811,0.003977,656954,3850099
...,...,...,...,...,...,...,...,...,...,...
5753790,rs5770824,22,51172460,C,T,0.0225,-0.004041,0.005831,715356,3850099
5753791,rs3810648,22,51175626,G,A,0.0613,0.001762,0.003547,739079,3850099
5753792,rs73174437,22,51177257,T,C,0.0348,-0.000743,0.004725,713374,3850099
5753793,rs2285395,22,51178090,A,G,0.0549,0.001494,0.003735,739077,3850099
5753794,rs56238942,22,51182399,G,A,0.0770,0.000592,0.003232,720624,3850099

Now this file is ok with some basic check and unified column names. 

Save to feather format for later use in python

In [24]:
filename.split(".")[0]

'GCST90449056'

In [25]:
parquet_path =  data_dir / "parquet"

parquet_path.mkdir(exist_ok=True, parents=True)
to_file = str(parquet_path/filename.split(".")[0])
sumstats.to_format(
        path=to_file,
        fmt="gwaslab", 
   tab_fmt = "parquet" 
)

2025/06/10 01:38:43 Start to convert the output sumstats in:  gwaslab  format
2025/06/10 01:38:44  -Start outputting sumstats in gwaslab format...
2025/06/10 01:38:44  -gwaslab format will be loaded...
2025/06/10 01:38:44  -gwaslab format meta info:
2025/06/10 01:38:44   - format_name  : gwaslab
2025/06/10 01:38:44   - format_source  : https://cloufield.github.io/gwaslab/
2025/06/10 01:38:44   - format_version  : 20231220_v4
2025/06/10 01:38:44  -Output path: /home/xutingfeng/job/finemap_tools/data/parquet/GCST90449056.gwaslab.parquet
2025/06/10 01:38:44  -Output columns: rsID,CHR,POS,EA,NEA,EAF,BETA,SE,N,STATUS
2025/06/10 01:38:44  -Writing sumstats to: /home/xutingfeng/job/finemap_tools/data/parquet/GCST90449056.gwaslab.parquet...
2025/06/10 01:38:48  -Saving log file to: /home/xutingfeng/job/finemap_tools/data/parquet/GCST90449056.gwaslab.log
2025/06/10 01:38:48 Finished outputting successfully!

## Reformat to other format

Sometimes we need to reformat the data to other format, such as ldsc or other format to load in other software.

### LDSC

In [28]:
filename = "GCST90449056.gwaslab.parquet"
to_load_file = parquet_path / filename

data = pd.read_parquet(to_load_file)
data

,rsID,CHR,POS,EA,NEA,EAF,BETA,SE,N,STATUS
0,rs3094315,1,752566,G,A,0.1637,-0.003855,0.002427,663139,3850099
1,rs4970452,1,885689,G,A,0.0537,-0.012647,0.004002,656956,3850099
2,rs4970376,1,885699,A,G,0.0544,-0.012867,0.003977,656954,3850099
3,rs4970375,1,886006,T,C,0.0543,-0.012928,0.003981,656955,3850099
4,rs3828047,1,887801,A,G,0.0544,-0.012811,0.003977,656954,3850099
...,...,...,...,...,...,...,...,...,...,...
5753790,rs5770824,22,51172460,C,T,0.0225,-0.004041,0.005831,715356,3850099
5753791,rs3810648,22,51175626,G,A,0.0613,0.001762,0.003547,739079,3850099
5753792,rs73174437,22,51177257,T,C,0.0348,-0.000743,0.004725,713374,3850099
5753793,rs2285395,22,51178090,A,G,0.0549,0.001494,0.003735,739077,3850099
5753794,rs56238942,22,51182399,G,A,0.0770,0.000592,0.003232,720624,3850099

Now turn it to gl.Sumstats

In [27]:
mysumstats = gl.Sumstats(
    data, 
    fmt = "gwaslab"
)
mysumstats.data

2025/06/10 01:42:11 GWASLab v3.6.3 https://cloufield.github.io/gwaslab/
2025/06/10 01:42:11 (C) 2022-2025, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2025/06/10 01:42:11 Python version: 3.9.23 | packaged by conda-forge | (main, Jun  4 2025, 17:57:12)
[GCC 13.3.0]
2025/06/10 01:42:11 Start to load format from formatbook....
2025/06/10 01:42:11  -gwaslab format meta info:
2025/06/10 01:42:11   - format_name  : gwaslab
2025/06/10 01:42:11   - format_source  : https://cloufield.github.io/gwaslab/
2025/06/10 01:42:11   - format_version  : 20231220_v4
2025/06/10 01:42:11 Start to initialize gl.Sumstats from pandas DataFrame ...
2025/06/10 01:42:12  -Reading columns          : EAF,EA,CHR,POS,rsID,SE,NEA,STATUS,N,BETA
2025/06/10 01:42:12  -Renaming columns to      : EAF,EA,CHR,POS,rsID,SE,NEA,STATUS,N,BETA
2025/06/10 01:42:12  -Current Dataframe shape : 5753795  x  10
2025/06/10 01:42:12  -Initiating a status column: STATUS ...
2025/06/10 01:42:12  #WARNING! Version of genomic coordinates is unknown...
2025/06/10 01:42:14 Start to reorder the columns...v3.6.3
2025/06/10 01:42:14  -Current Dataframe shape : 5753795 x 10 ; Memory usage: 356.19 MB
2025/06/10 01:42:14  -Reordering columns to    : rsID,CHR,POS,EA,NEA,EAF,BETA,SE,N,STATUS
2025/06/10 01:42:14 Finished reordering the columns.
2025/06/10 01:42:14  -Column  : rsID   CHR   POS   EA       NEA      EAF     BETA    SE      N     STATUS
2025/06/10 01:42:14  -DType   : string Int64 Int64 category category float32 float64 float64 Int64 category
2025/06/10 01:42:14  -Verified: T      T     T     T        T        T       T       T       T     T
2025/06/10 01:42:14  -Current Dataframe memory usage: 356.19 MB
2025/06/10 01:42:14 Finished loading data successfully!

,rsID,CHR,POS,EA,NEA,EAF,BETA,SE,N,STATUS
0,rs3094315,1,752566,G,A,0.1637,-0.003855,0.002427,663139,9999999
1,rs4970452,1,885689,G,A,0.0537,-0.012647,0.004002,656956,9999999
2,rs4970376,1,885699,A,G,0.0544,-0.012867,0.003977,656954,9999999
3,rs4970375,1,886006,T,C,0.0543,-0.012928,0.003981,656955,9999999
4,rs3828047,1,887801,A,G,0.0544,-0.012811,0.003977,656954,9999999
...,...,...,...,...,...,...,...,...,...,...
5753790,rs5770824,22,51172460,C,T,0.0225,-0.004041,0.005831,715356,9999999
5753791,rs3810648,22,51175626,G,A,0.0613,0.001762,0.003547,739079,9999999
5753792,rs73174437,22,51177257,T,C,0.0348,-0.000743,0.004725,713374,9999999
5753793,rs2285395,22,51178090,A,G,0.0549,0.001494,0.003735,739077,9999999
5753794,rs56238942,22,51182399,G,A,0.0770,0.000592,0.003232,720624,9999999

In [33]:
ldsc_dir = data_dir / "ldsc"
ldsc_dir.mkdir(exist_ok=True, parents=True)
to_file = str(ldsc_dir/filename.split(".")[0])
mysumstats.to_format(to_file,fmt="ldsc",hapmap3=False,exclude_hla=True,md5sum=True)

2025/06/10 01:44:06 Start to convert the output sumstats in:  ldsc  format
2025/06/10 01:44:07  -Excluded 32666 variants in HLA region (chr6: 25000000-34000000 )...
2025/06/10 01:44:07  -Formatting statistics ...
2025/06/10 01:44:13  -Float statistics formats:
2025/06/10 01:44:13   - Columns       : ['EAF', 'BETA', 'SE']
2025/06/10 01:44:13   - Output formats: ['{:.4g}', '{:.4f}', '{:.4f}']
2025/06/10 01:44:13  -Start outputting sumstats in ldsc format...
2025/06/10 01:44:13  -ldsc format will be loaded...
2025/06/10 01:44:13  -ldsc format meta info:
2025/06/10 01:44:13   - format_name  : ldsc
2025/06/10 01:44:13   - format_source  : https://github.com/bulik/ldsc/wiki/Summary-Statistics-File-Format
2025/06/10 01:44:13   - format_source2  : https://github.com/bulik/ldsc/blob/master/munge_sumstats.py
2025/06/10 01:44:13   - format_version  :  20150306
2025/06/10 01:44:13  -gwaslab to ldsc format dictionary:
2025/06/10 01:44:13   - gwaslab keys: rsID,NEA,EA,EAF,N,BETA,P,Z,INFO,OR,CHR,POS
2025/06/10 01:44:13   - ldsc values: SNP,A2,A1,Frq,N,Beta,P,Z,INFO,OR,CHR,POS
2025/06/10 01:44:13  -Output path: /home/xutingfeng/job/finemap_tools/data/ldsc/GCST90449056.noMHC.ldsc.tsv.gz
2025/06/10 01:44:15  -Output columns: SNP,CHR,POS,A1,A2,Frq,Beta,N
2025/06/10 01:44:15  -Writing sumstats to: /home/xutingfeng/job/finemap_tools/data/ldsc/GCST90449056.noMHC.ldsc.tsv.gz...
2025/06/10 01:44:15   -Fast to csv mode...
2025/06/10 01:44:21  -md5sum hashing for the file: /home/xutingfeng/job/finemap_tools/data/ldsc/GCST90449056.noMHC.ldsc.tsv.gz
2025/06/10 01:44:21  -md5sum path: /home/xutingfeng/job/finemap_tools/data/ldsc/GCST90449056.noMHC.ldsc.tsv.gz.md5sum
2025/06/10 01:44:21  -md5sum: 2bef770e0fb52e1b3188773807ab04f7
2025/06/10 01:44:22  -Saving log file to: /home/xutingfeng/job/finemap_tools/data/ldsc/GCST90449056.noMHC.ldsc.log
2025/06/10 01:44:22 Finished outputting successfully!

In [32]:
to_file = str(ldsc_dir/filename.split(".")[0])
to_file

'/home/xutingfeng/job/finemap_tools/data/ldsc/GCST90449056'

## other situation

- if not GRCh38, use `versionConvert.py`
- if no rsid , at least should have `variant_id` columns with `chr:pos:ref:alt` format [sorted of ref and alt] by `resetID2.py`.

> why ref:alt should be sorted?  Reason: 1) ref and alt may are presented as A1 A2 or EA NEA etc, which we can not make sure which one are ref and alt or this is not important for variant name, as this is working as mapping between different variant name.

For preprocessing stage, we recommend to be consistent format with columns or varaint name, but not preprocess with variants to keep or rm, which this should be done in downstream analysis.